Project2.Web/Models/ProjectViewModel.cs
using Project2.Core.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Project2.Web.Models
{
    public class ProjectViewModel
    {
        public int id { get; set; }
        public string name { get; set; }
        public DateTime create_at { get; set; }
        public DateTime update_at { get; set; }
        public bool isActive { get; set; }
        public string require { get; set; }
        public Tag Tag { get; set; }
        public List<int> Tags { get; set; }
        public string tagName { get; set; }
        public string studentId { get; set; }
        public string studentName { get; set; }
        public string timeStartId { get; set; }
        public List<Report> Reports { get; set; }
    }
}

Project2.Web/Controllers/ProjectController.cs
using Project2.Core.Interfaces.IServices;
using Project2.Core.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using Project2.Web.Models;
using Project2.Core.Models.Entities;
using Project2.Web.Common;

namespace Project2.Web.Controllers
{
    public class ProjectController : Controller
    {
        // GET: Project
        private readonly IProjectService projectService;
        private readonly ITagService tagService;
        private readonly ITimeStartService timeStartService;
        private readonly IGuestService guestService;
        private readonly IReportService reportService;
        private IDataContext dataContext;

        public ProjectController(IProjectService projectService, IDataContext dataContext, ITagService tagService, ITimeStartService timeStartService, IGuestService guestService, IReportService reportService)
        {
            this.projectService = projectService;
            this.dataContext = dataContext;
            this.tagService = tagService;
            this.timeStartService = timeStartService;
            this.guestService = guestService;
            this.reportService = reportService;
        }

        public ActionResult Index()
        {
           
            var listTag = tagService.GetTags().ToList();
            
            ViewBag.listTag = new SelectList(listTag, "id", "name");
            
            return View();
        }

        public ActionResult projectPartialView(string key)
        {
            var userLogin = (UserLogin)Session["userId"];
            var model = projectService.getListProjectById(userLogin.id, key);
            return PartialView("projectPartialView", model);
        }

        public ActionResult sidebarPartialView()
        {
            var userLogin = (UserLogin)Session["userId"];
            var guest = guestService.GetGuestById(userLogin.id);
            ViewBag.guest = guest;
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult addProject(ProjectViewModel model)
        {
            var time = timeStartService.getTime();
            var obj = (UserLogin)Session["userId"];
            var teacher = guestService.GetGuestById(obj.id);
            var cProjectTeach = projectService.getCountProjectByIdTeach(obj.id);
            bool check = projectService.getNameProject(model.name);
            if (ModelState.IsValid)
            {
                try
                {
                    if (model.id == 0)
                    {
                        if(cProjectTeach > 8)
                        {
                            ViewBag.message = "Thêm lỗi, số lượng đề tài tối đa là 8";
                            return RedirectToAction("projectPartialView", "Project");
                        }
                        if(check == false)
                        {
                            return RedirectToAction("projectPartialView", "Project");
                        }
                        else
                        {
                            var data = new Project();
                            data.name = model.name;
                            data.require = model.require;
                            data.time_Start = time;
                            data.GuestTeacher = teacher;
                            dataContext.Projects.Add(data);
                            dataContext.SaveChanges();

                            var projectId = data.id;
                            var newProject = projectService.getProjectById(projectId);
                            data.Tags = new List<Tag>();
                            foreach (var items in model.Tags)
                            {
                                var tag = dataContext.Tags.Include(x => x.Projects).Where(x => x.id.Equals(items)).SingleOrDefault();

                                var i = tag.Projects;
                                if (tag != null)
                                {
                                    data.Tags.Add(tag);
                                }
                            }
                            dataContext.SaveChanges();
                            return RedirectToAction("projectPartialView", "Project");
                        }                        
                    }
                }
                catch (Exception e) {
                    throw e;
                }
            }
            return RedirectToAction("Index", "Project");
        }

        
        public ActionResult removeProject(int id)
        {
            var data = dataContext.Projects.Find(id);
            dataContext.Projects.Remove(data);
            dataContext.SaveChanges();
            return RedirectToAction("projectPartialView", "Project");
        }

        public ActionResult loadReport(int id)
        {
            var project = projectService.getProjectById(id);
            ViewBag.name = project.name;

            ViewBag.id = project.id;
            return View();
        }

        [HttpGet]
        public PartialViewResult reportPartialViewInTeacher(int id)
        {
            var model = reportService.GetReports(id);
            return PartialView("reportPartialViewInTeacher", model);
        }

        [HttpGet]
        [ValidateInput(false)]
        public ActionResult changeStatus(int id)
        {            
            var model = reportService.getReportById(id);
            model.isSeen = true;
            dataContext.SaveChanges();
            var myModel = reportService.GetReports(model.Project.id);
            return PartialView("reportPartialViewInTeacher", myModel);
        }

        public ActionResult loadReportDetail(int id)
        {
            var model = reportService.getReportById(id);
            model.isSeen = true;
            dataContext.SaveChanges();
            return View(model);
        }
    }
}

Project2.Web/Controllers/TagController.cs
using Project2.Core.Interfaces.IServices;
using Project2.Core.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project2.Core.Models.Entities;
using Project2.Web.Models;

namespace Project2.Web.Controllers
{
    public class TagController : Controller
    {
        // GET: Tag
        private readonly ITagService tagService;

        private IDataContext dataContext;

        public TagController(ITagService tagService, IDataContext dataContext)
        {
            this.tagService = tagService;
            this.dataContext = dataContext;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult addTag(ProjectViewModel model)
        {
            if (ModelState.IsValid)
            {
                if(model.id == 0)
                {
                    var data = new Tag();
                    data.name = model.tagName;
                    dataContext.Tags.Add(data);
                    dataContext.SaveChanges();
                    return RedirectToAction("Index", "Project");
                }
            }
            return RedirectToAction("Index", "Project");
        }
    }
}

Project2.Web/Views/Project/Index.cshtml
@model Project2.Web.Models.ProjectViewModel
@{
    Layout = "~/Views/Shared/_LayoutTeacher.cshtml";
}


<div class="row">
    <!-- Danh mục đồ án  -->
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="content-box__name mb-3 pb-2">Danh Mục Đồ Án</div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="index-box py-3 pb-3 ml-3 d-flex justify-content-start align-items-center">
            <button class="btn btn-custom btn-create" data-toggle="modal" data-target="#modifyProject">Tạo ngay</button>
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-bordered table-hover" id="tableProject">
            @Html.Action("projectPartialView", "Project")
        </table>
    </div>


    <div class="modal fade" id="modifyProject" tabindex="-1" role="dialog"
         aria-labelledby="modifyProject" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            @using (Html.BeginForm("AddProject", "Project", FormMethod.Post, new { onsubmit = "return addProject(this)" }))
            {
                <div class="modal-content">

                    <div class="modal-header">
                        <h5 class="modal-title">Tạo đồ án môn học</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    <label>Tên đồ án</label>
                                    @Html.EditorFor(x => x.name, new { htmlAttributes = new { @class = "form-control", type = "text", required = "required" } })
                                    @Html.ValidationMessageFor(x => x.name, "", new { @class = "text-danger" })
                                    <small id="helpId" class="text-muted">Tên đồ án cho sinh viên</small>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="row">
                                    <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
                                        <div class="form-group">
                                            <label>Sử dụng ngôn ngữ</label>
                                            @Html.DropDownListFor(x => x.Tags, (IEnumerable<SelectListItem>)ViewBag.listTag, new { @class = "form-control", @id = "select-tag", @multiple = "true" })
                                            <small id="helpId" class="text-muted">Ngôn ngữ được sử dụng cho đồ án</small>
                                        </div>
                                    </div>

                                    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                                        <div class="form-group">
                                            <label>Thêm Ngôn ngữ</label><br>
                                            <button type="button" class="btn btn-secondary btn-addTag form-control" data-toggle="modal" data-target="#createTag">Thêm</button>
                                        </div>
                                    </div>


                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <label>Các yêu cầu</label>
                                @Html.TextAreaFor(x => x.require, new { @class = "projectContent" })
                                @Html.ValidationMessageFor(x => x.require, "", new { @class = "text-danger" })
                                <small id="helpId" class="text-muted">Các yêu cầu được sử dụng cho đồ án</small>
                            </div>

                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary"
                                data-dismiss="modal">
                            Close
                        </button>
                        <input type="submit" class="btn btn-primary" data-toggle="modal"
                               data-target="#Table" value="Xác nhận" />
                    </div>
                </div>
            }

        </div>
    </div>

    <div class="modal fade" id="createTag" tabindex="-1" role="dialog"
         aria-labelledby="createTag" aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            @using (Html.BeginForm("", "", FormMethod.Post, new { @id = "formTag", onsubmit = "return addTag(this)" }))
            {
                <div class="modal-content">

                    <div class="modal-header">
                        <h5 class="modal-title">Tạo Tag</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="row">

                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    <label>Tên Ngôn ngữ</label>
                                    @Html.EditorFor(x => x.tagName, new { @class = "form-control", @require = "require", @type = "text" })
                                    @Html.ValidationMessageFor(x => x.Tags, "", new { @class = "text-danger" })
                                    <small id="helpId" class="text-muted">Tên ngôn ngữ được sử dụng cho đồ án</small>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary"
                                data-dismiss="modal">
                            Close
                        </button>
                        <button type="submit" class="btn btn-primary" data-toggle="modal"
                                data-target="#Table">
                            Xác nhận
                        </button>
                    </div>
                </div>
            }

        </div>
    </div>

</div>

@section scripts{
    @*<script src="~/Scripts/tinyMCE/tinymce.min.js"></script>*@
    <script src="~/Scripts/tinyMCE/tinymce.min.js"></script>
    <script>
        $("#select-tag").select2({
            placeholder: "Chọn ngôn ngữ",
            tags: true,
            tokenSeparators: ['/', ',', ',', " "]
        });
        tinymce.init({
            selector: 'textarea',
            width: "100%",
            height: "300px",

            entity_encoding: "raw",
            menubar: false,

            relative_urls: false,
            inline_styles: true,
            image_advtab: true,
            branding: false,
           
            plugins: [
                'advlist autolink lists link image charmap print preview anchor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table contextmenu paste code colorpicker textcolor ',
                'wordcount'
            ],
            toolbar: 'link  image| alignleft aligncenter alignright alignjustify | styleselect | bold italic | forecolor | backcolor  | bullist numlist outdent indent  ',
            toolbar_location: 'bottom'

        });

        function removeProject() {
            swal({
                title: "Bạn có chắc muốn xóa!",
                text: "Dữ liệu sẽ không được khôi phục!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: 'red',
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: "No, cancel plx!",
                closeOnConfirm: false,
                closeOnCancel: false
            },
                function (isConfirm) {
                    if (isConfirm) {
                        swal("Deleted!", "Your imaginary file has been deleted!", "success");
                    } else {
                        swal("Cancelled", "Your imaginary file is safe :)", "error");
                    }
                }
            )
        }

        function addProject(form) {


            var url = "@Url.Action("addProject", "Project")";
            var name = $("#name").val();
            var require = tinymce.get("require").getContent();
            var arr = [];

            $.each($("#select-tag option:selected"), function () {
                arr.push($(this).val());
            });

            $.ajax({
                url: url,
                type: "POST",
                data: {
                    name: name,
                    require: require,
                    Tags: arr
                },
                success: function (response) {
                    $("#modifyProject").modal("hide");
                    $("#tableProject").html(response);  
                    swal("success!", "Thêm đồ án thành công", "success");
                },
                error: function (xhr, status, error) {
                    swal("Lỗi!", "Thêm thất bại", "Error");
                }
            })

        }

        function addTag(form) {

            var url = "@Url.Action("addTag", "Tag")";
            $.ajax({
                url: url,
                type: "POST",
                success: function () {
                    swal("success!", "Thêm Tag thành công", "success");
                }
            })
        }

        function removeProject(id) {

            var url = "@Url.Action("removeProject", "Project")/"+id;
            $.ajax({
                url: url,
                type: "POST",
                contentType: "html",

                success: function (response) {
                    swal("success!", "Xóa đồ án thành công", "success");
                    $("#tableProject").html(response);
                }
            })
        }
    </script>
}

Project2.Web/Views/Project/loadReport.cshtml
@model Project2.Core.Models.Entities.Report
@{
    Layout = "~/Views/Shared/_LayoutTeacher.cshtml";
}

<div class="row">
    <div class="w-100">
        <ul class="breadcrumb breadcrumb-custom">
            <li class="breadcrumb-item"><a href="#">Danh Sách Đồ Án</a></li>
            <li class="breadcrumb-item active"><a href="#">@ViewBag.name</a></li>
        </ul>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="heading d-flex flex-row justify-content-between p-2 mb-2 align-content-around">
            <div class="heading-title h4">Danh Sách báo cáo</div>
            <div class="heading-services d-flex">
                <input type="text" class="form-control mr-2" placeholder="search">
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-hover" id="tableReport">
            @Html.Action("reportPartialViewInTeacher", "Project", new { id = ViewBag.id })
        </table>
    </div>

</div>

@section scripts{
<script>
    function changeStatus(id) {
        var url = "@Url.Action("changeStatus", "Project")/" + id;
        $.ajax({
            url: url,
            contentType: "html",
            type: "GET",
            success: function (response) {
                $("#tableReport").html(response);
            }
        });
    }
    </script>
    }

Project2.Web/Views/Project/loadReportDetail.cshtml
@model Project2.Core.Models.Entities.Report
@{
    Layout = "~/Views/Shared/_LayoutTeacher.cshtml";
    string s = Model.create_at.ToString();
}
<div class="row">
    <div class="w-100">
        <ul class="breadcrumb breadcrumb-custom">
            <li class="breadcrumb-item"><a href="#">Danh Sách Đồ Án</a></li>
            <li class="breadcrumb-item"><a href="#">Quản lý sinh viên</a></li>
            <li class="breadcrumb-item active"><a href="#">@Model.title</a></li>
        </ul>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="heading d-flex flex-column p-2 mb-2 align-content-around">
            <div class="heading-title h3">@Model.title</div>
            <div class="heading-by">up load by @Model.Project.GuestStudent.Full_name - @Model.create_at</div>
        </div>
    </div>


    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="content-render">
            
            @Html.Raw(Model.content)
        </div>
        <div class="back">
            <a href="@Url.Action("loadReport", "Project", new { id = Model.Project.id })">&prec; Trở về trang thông báo</a>
        </div>
    </div>
</div>

Project2.Web/Views/Project/projectPartialView.cshtml
@model List<Project2.Core.Models.Entities.Project>

<thead>
    <tr>
        <th>#</th>
        <th>Tên đồ án</th>
        <th>Danh mục ngôn ngữ</th>
        <th>Danh mục yêu cầu</th>
        <th>Sinh viên đăng ký</th>
        <th>Action</th>
    </tr>
</thead>
<tbody>
    @{
        int index = 0;
    }
    @if (Model.Count == 0)
    {
        <tr>
            <td style="color: red" colspan="6" align="center">Dữ liệu trống...</td>
        </tr>
    }
    @foreach (var item in Model)
    {
        index++;
        <tr>
            <td>@index</td>
            <td>@item.name</td>
            <td>
                @foreach (var i in item.Tags)
                {
                    <span>@i.name.ToString(), </span>
                }
            </td>
            <td>
                @Html.Raw(item.require)
            </td>
            
            <td>
                @if (item.GuestStudent == null)
                {
                    <p></p>
                }
                else {
                    <span>@item.GuestStudent.Full_name.ToString()</span>
                }</td>
            <td>
                <a href="#" class="btn btn-danger btn-sm" onclick="removeProject(@item.id)"><i class="fas fa-trash-alt"></i></a>
                <a href="@Url.Action("loadReport", "Project", new { id = item.id })" class="btn btn-info btn-sm"><i class="fas fa-eye"></i></a>
            </td>
        </tr>
    }
</tbody>

Project2.Web/Views/Project/reportPartialViewInTeacher.cshtml
@model List<Project2.Core.Models.Entities.Report>
@{ 
    Layout = null;
}
<thead>
    <tr>
        <th>#</th>
        <th>Tên đồ án</th>
        <th>Sinh viên đăng ký</th>
        <th>Tiêu đề</th>
        <th>Ngày lập</th>
        <th>Trạng thái</th>
        <th>Action</th>
    </tr>
</thead>
<tbody>
    @if (Model.Count == 0)
    {
        <tr>
            <td colspan="7" style="color: red;">Dữ liệu trống...</td>
        </tr>
                }
                else
                {
                    int index = 0;
                    foreach (var item in Model)
                    {
                        index++;
            <tr>
                <td>@index</td>
                <td>@item.Project.name</td>
                <td>@item.Project.GuestStudent.Full_name</td>
                <td>@item.title</td>
                <td>@((DateTime.Now - item.create_at).Days) trước</td>
                <td>
                                @(item.isSeen ?  "Đã xem" : "Chưa xem" )
                            </td>
            
                            <td>
                                @if (item.isSeen)
                                {
                        <button type="button" class="btn btn-success btn-sm btn-unable" disabled><i class="fas fa-check"></i></button>
                    }
                    else
                    {
                        <button type="button" onclick="changeStatus(@item.id)" class="btn btn-success btn-sm"><i class="fas fa-check"></i></button>
                    }
                    <a href="@Url.Action("loadReportDetail", "Project", new { id = item.id  })" class="text-white btn btn-info btn-sm"><i class="fas fa-eye"></i></a>
                </td>
            </tr>
        }

    }

</tbody>

Project2.Web/Views/Project/sidebarPartialView.cshtml
@{ 
    Layout = null;
}

<div class="sidebar shadow-right">
    <div class="p-3">
        <div class="logo d-flex justify-content-center align-items-center">
            <a href="#">Quản Lý Đồ Án</a>
        </div>
        <div class="profile-box d-flex justify-content-start align-items-center pl-3">
            <img src="~/Content/asset/public/Image/@ViewBag.guest.Path" alt="User profile" width="50" class="mr-3" style="border-radius:50%">
            <div class="profile-box__content d-flex flex-column">
                <div class="wc">Hello, <span>@ViewBag.guest.Full_name</span></div>
                <div class="type">Online <span><i class="fas fa-check text-success"></i></span></div>
            </div>
        </div>
        <hr>
        <div class="list-box">
            <div class="list-title px-2 mb-2">dashboard</div>
            <ul class="d-flex flex-column justify-content-center align-items-center">
                <li class="d-flex flex-row list-item mb-2 active">
                    <a class="list-link px-2" href="@Url.Action("Index", "Project")">
                        <span class="icon mr-2">
                            <i class="fas fa-rainbow"></i>
                        </span>
                        <span class="list-link-content">Trang chủ</span>
                    </a>
                </li>
            </ul>
        </div>
        <hr>
        <div class="list-box">
            <div class="list-title px-2 mb-2">Chức năng</div>
            <ul class="d-flex flex-column justify-content-center align-items-center">
                <li class="d-flex flex-row list-item mb-2">
                <li class="d-flex flex-row list-item mb-2">
                    <a class="list-link px-2">
                        <span class="icon mr-2">
                            <i class="fas fa-rainbow"></i>
                        </span>
                        <span class="list-link-content">Xem báo cáo tiến độ</span>
                    </a>
                </li>
            </ul>
        </div>
        <hr>
        <div class="footer">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    Copyright &copy; By <a href="#" class="footer-text">Dev99</a>
                </div>
            </div>
        </div>
    </div>
</div>